version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bayview"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tqh87inasdrr"
s3_prefix = "bayview"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

